mysql:
    path: 127.0.0.1
    port: "3306"
    db-name:
    username: root
    password:
    max-idle-conns: 10
    max-open-conns: 100
pgsql:
    path: ""
    port: ""
    db-name: ""
    username: ""
    password: ""
    max-idle-conns: 0
    max-open-conns: 0
sqlite:
    path: ./
    port: ""
    db-name: steins
    username: ""
    password: ""
    max-idle-conns: 0
    max-open-conns: 0
system:
    port: "18888"
    db-type: mysql
    oss-type: aliyun
    context-path: /steins/go
zap:
    level: info
    prefix: '[gin-react-app]'
    format: console
    director: log
    encodelevel: LowercaseLevelEncoder
    showline: true
    loginconsole: true
