definitions:
  request.AddSystemUserRequest:
    properties:
      domain_id:
        description: 域id
        type: integer
      is_admin:
        description: 是否为管理员
        type: boolean
      nickname:
        description: 昵称
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - domain_id
    - is_admin
    - nickname
    - password
    - username
    type: object
  request.DBConnectionRequest:
    properties:
      dbType:
        description: 数据库类型
        type: string
      host:
        description: 服务器地址
        type: string
      password:
        description: 密码
        type: string
      port:
        description: 端口
        type: string
      username:
        description: 用户名
        type: string
    required:
    - dbType
    - password
    - username
    type: object
  request.InitProjectRequest:
    properties:
      adminAccount:
        description: 管理员账号
        type: string
      adminPassword:
        description: 管理员密码
        type: string
      dbName:
        description: 数据库名
        type: string
      dbType:
        description: 数据库类型
        type: string
      host:
        description: 服务器地址
        type: string
      password:
        description: 密码
        type: string
      port:
        description: 端口
        type: string
      username:
        description: 用户名
        type: string
    required:
    - adminAccount
    - adminPassword
    - dbName
    - dbType
    - password
    - username
    type: object
  request.PwdLogin:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  request.SystemUserPageRequest:
    properties:
      account:
        description: 账户名称
        type: string
      current:
        description: 当前页
        type: integer
      is_admin:
        description: 是否管理员
        type: boolean
      nickname:
        description: 昵称
        type: string
      pageSize:
        description: 页数据量
        type: integer
      status:
        description: 账号状态
        type: integer
    type: object
  response.CheckResult:
    properties:
      result:
        type: boolean
    type: object
  response.PageResult-response_SystemUserPageVo:
    properties:
      current:
        description: 当前页
        type: integer
      pageSize:
        description: 每页条数
        type: integer
      records:
        description: 数据列表
        items:
          $ref: '#/definitions/response.SystemUserPageVo'
        type: array
      total:
        description: 总记录数
        type: integer
    type: object
  response.Response-any:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      msg:
        example: 成功
        type: string
    type: object
  response.Response-bool:
    properties:
      code:
        example: 200
        type: integer
      data:
        type: boolean
      msg:
        example: 成功
        type: string
    type: object
  response.Response-response_CheckResult:
    properties:
      code:
        example: 200
        type: integer
      data:
        $ref: '#/definitions/response.CheckResult'
      msg:
        example: 成功
        type: string
    type: object
  response.Response-response_PageResult-response_SystemUserPageVo:
    properties:
      code:
        example: 200
        type: integer
      data:
        $ref: '#/definitions/response.PageResult-response_SystemUserPageVo'
      msg:
        example: 成功
        type: string
    type: object
  response.Response-response_SystemUserVo:
    properties:
      code:
        example: 200
        type: integer
      data:
        $ref: '#/definitions/response.SystemUserVo'
      msg:
        example: 成功
        type: string
    type: object
  response.SystemUserPageVo:
    properties:
      domainName:
        description: 所属域
        type: string
      email:
        description: 邮箱
        type: string
      isAdmin:
        description: 是否为管理员
        type: boolean
      nickname:
        description: 昵称
        type: string
      phone:
        description: 手机号
        type: string
      status:
        description: 状态
        type: integer
      userId:
        description: 用户id
        type: integer
    type: object
  response.SystemUserVo:
    properties:
      email:
        description: 邮箱
        type: string
      isAdmin:
        description: 是否为管理员
        type: boolean
      nickname:
        description: 昵称
        type: string
      phone:
        description: 手机号
        type: string
      token:
        description: token
        type: string
      userId:
        description: 用户id
        type: integer
    type: object
info:
  contact: {}
  description: This is a sample server for Gin Swagger.
  title: Gin Swagger Demo API
  version: "1.0"
paths:
  /auth/admin_pwd_login:
    post:
      consumes:
      - application/json
      operationId: adminPwdLogin
      parameters:
      - description: 密码登录参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.PwdLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-response_SystemUserVo'
      summary: 管理端密码登录
      tags:
      - authController
  /auth/logout:
    post:
      consumes:
      - application/json
      operationId: userLogout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-any'
      summary: 用户退出登录
      tags:
      - authController
  /auth/pwd_login:
    post:
      consumes:
      - application/json
      operationId: userPwdLogin
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-any'
      summary: 用户端密码登录
      tags:
      - authController
  /init/check:
    get:
      consumes:
      - application/json
      operationId: checkNeedInit
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-response_CheckResult'
      summary: 查看是否需要初始化
      tags:
      - initController
  /init/init_project:
    post:
      consumes:
      - application/json
      description: 当配置文件的数据库配置为空时，需要进行项目初始化
      operationId: initProject
      parameters:
      - description: 初始化相关参数
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.InitProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-any'
      summary: 项目初始化
      tags:
      - initController
  /init/test_db_connection:
    post:
      consumes:
      - application/json
      operationId: testDBConnection
      parameters:
      - description: 测试数据库连接相关参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.DBConnectionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-response_CheckResult'
      summary: 测试数据库是否能够连接
      tags:
      - initController
  /user/add:
    post:
      consumes:
      - application/json
      operationId: addSystemUser
      parameters:
      - description: 添加用户请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.AddSystemUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-bool'
      summary: 添加用户信息
      tags:
      - systemUserController
  /user/get_info:
    get:
      consumes:
      - application/json
      operationId: getUserInfo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-response_SystemUserVo'
      summary: 获取登录用户信息
      tags:
      - systemUserController
  /user/get_page:
    post:
      consumes:
      - application/json
      operationId: getSystemUserPageData
      parameters:
      - description: 获取用户页数据请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.SystemUserPageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-response_PageResult-response_SystemUserPageVo'
      summary: 添加用户信息
      tags:
      - systemUserController
swagger: "2.0"
